version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-avantys
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "15672:15672" # RabbitMQ management UI port
      - "5672:5672"   # RabbitMQ AMQP port
    env_file:
      - .env

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql
    environment:
      SA_PASSWORD: "MelvinIsEenBot34"
      ACCEPT_EULA: "Y"
    ports:
      - 1436:1433

  guidance-management-service:
    build:
      context: ./guidance-management
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./guidance-management:/usr/src/guidance-management
    depends_on:
      - sqlserver
      - rabbitmq

  registrationmanagementapi:
    image: avantys-education/registrationmanagementapi:1.0
    build: registration-management-api
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"
        
  test-management-api:
    image: ${DOCKER_REGISTRY-}test-management
    build:
      context: ./test-management
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3004:3004"
    depends_on:
      - sqlserver
      - rabbitmq
       
  study-program-management-read-api:
    image: ${DOCKER_REGISTRY-}study-program-management-read
    build:
      context: ./study-program-management/StudyProgramManagement_Read
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3006:3006" 
    depends_on:
      - mongodb
      - rabbitmq

  study-program-management-write-api:
    image: ${DOCKER_REGISTRY-}study-program-management-write
    build:
      context: ./study-program-management/StudyProgramManagement_Write
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3005:3005" 
    depends_on:
      - sqlserver
      - rabbitmq

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  
         
volumes:
  mongodb_data:
  sqlserverdata:
  rabbitmqdata:
    external: true