version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-avantys
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "15672:15672" # RabbitMQ management UI port
      - "5672:5672"   # RabbitMQ AMQP port
    env_file:
      - .env

  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: sqlserver
      volumes:
        - sqlserverdata:/var/opt/mssql
      environment:
        SA_PASSWORD: "MelvinIsEenBot34"
        ACCEPT_EULA: "Y"
      ports:
        - 1436:1433

  registrationmanagementapi:
    image: avantys-education/registrationmanagementapi:1.0
    build: registration-management-api
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

volumes:
  sqlserverdata:
  rabbitmqdata:
    external: true