version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-avantys
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "15672:15672" # RabbitMQ management UI port
      - "5672:5672"   # RabbitMQ AMQP port
    env_file:
      - .env

  # sqlserver:
  #   image: mcr.microsoft.com/azure-sql-edge
  #   container_name: sqlserver-avantys
  #   volumes:
  #     - sqlserverdata:/var/opt/mssql
  #   ports:
  #     - "1434:1433"
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_PID=Developer
  #     - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  registrationmanagementapi:
    image: avantys-education/registrationmanagementapi:1.0
    build: registration-management-api
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

volumes:
  # sqlserverdata:
  #   external: true
  rabbitmqdata:
    external: true